---
pki_country: FR
pki_state: Occitanie
pki_locality: Toulouse
domain: kthw.local

etcd_client_port: '2379'
etcd_peer_port: '2380'

kube_version: 1.34.0
kube_base_url: https://dl.k8s.io/v{{ kube_version }}/bin/linux/amd64
kube_cluster_name: kthw
kube_pod_cidr: 10.200.0.0/16
kube_cluster_ip_base_network: 10.32.0
kube_cluster_ip_cidr: '{{ kube_cluster_ip_base_network }}.0/24'
kube_node_port_range: 30000-32767

kube_apiserver_cluster_ip: '{{ kube_cluster_ip_base_network }}.1'
kube_apiserver_port: 6443

kube_dns_cluster_ip: '{{ kube_cluster_ip_base_network }}.10'