---
etcd_version: 3.6.4
etcd_url: https://github.com/etcd-io/etcd/releases/download/v{{ etcd_version }}/etcd-v{{ etcd_version }}-linux-amd64.tar.gz

runc_version: 1.3.3
runc_url: https://github.com/opencontainers/runc/releases/download/v{{ runc_version }}/runc.amd64

containerd_version: 2.2.0
containerd_url: https://github.com/containerd/containerd/releases/download/v{{ containerd_version }}/containerd-{{ containerd_version }}-linux-amd64.tar.gz
